### ISSUE TITLE
Full namespace path to controller. 

### ISSUE THREAD

**Issue by Alekc** [Haehnchen/idea-php-laravel-plugin#35]
Related to https://github.com/Haehnchen/idea-php-laravel-plugin/issues/31 

In 0.8 controllers are referenced by their full namespace path if the namespace has been changed from default. 

![screenshot](http://i.imgur.com/PEH6VSK.png)

How to replicate:

create new laravel project and enable php laravel plugin 

Routes are functioning as expected. 

run 
php artisan app:name TestApp

Routes are fetched with full namespace now.

**Comment by darthmaim** [comment]
This probably fails because `\\App\\Providers\\RouteServiceProvider` doesn't exist (it's now called `\\TestApp\\Providers\\RouteServiceProvider`) in the method you get the default namespace from: [src/de/espend/idea/laravel/controller/ControllerCollector.java#L61](https://github.com/Haehnchen/idea-php-laravel-plugin/blob/master/src/de/espend/idea/laravel/controller/ControllerCollector.java#L61)

**Comment by anugupta** [comment]
Yeah, I'm seeing this as well - the autocompletion uses the full namespace, and if the full namespace is used, then you can navigation to the controller with cmd+click.

However, if you don't use the full namespace (eg `Route::get('about','PagesController@about');`), then this works, but PHPStorm can't navigate to the declaration

**Comment by iLeoDo** [comment]
how about make the app namespace as a setting option?

**Comment by Haehnchen** [comment]
using `\Illuminate\Foundation\Support\Providers\RouteServiceProvider` now, also add custom settings textfield
